### PR TITLE
Add Typescript definition

### PR DESCRIPTION
**Pull request by DenisCarriere**
**Added Typescript definition** https://github.com/mapbox/geojson-merge/pull/12/commits/ac1d346473384079fda8e96ab513efec35cd9b4b

- Tests included `test/types.ts` via `npm run types`.

**Dev Dependencies** https://github.com/mapbox/geojson-merge/pull/12/commits/235a5b6c03c6aa62cf996bad6e8fe6c6c846f4c4

- Remove `stream-concat` dependency
- Moved testing dependencies to Dev
- Change `@mapbox` namespaces

**Add JSDocs on primary function** https://github.com/mapbox/geojson-merge/pull/12/commits/a9eb971b73c3e7dcdbf61fbee8ae7d8de93d555d

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@tmcw Whenever you got two minutes to review this, cheers!

**Comment by tmcw** [comment]
I'm starting to think that the API of this module should have expanded rather than overloaded the main function: there's an issue that the signature of geojsonMerge is:

```
geojsonMerge([featureCollection, featureCollection...], { stream: true }); // -> stream of Features
geojsonMerge([Points, Feature, featureCollection...], { stream: true }); // -> FeatureCollection
```

These are just two totally different methods that shouldn't go through the same signature, and would be hard or impossible to document faithfully in TypeScript or Flow. I'm going to cut a quick revision and give you something more consistent to target.

**Comment by DenisCarriere** [comment]
I've also noticed a few issues when enabling the `{stream: true}` option.

Great stuff, I'll wait out for the new revision before submitting any more changes.

**Comment by DenisCarriere** [comment]
Closing due to new PR https://github.com/mapbox/geojson-merge/pull/14

**Pull request closed without merging**
